{% set version = '0.2.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sparsevctrs
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/sparsevctrs_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sparsevctrs/sparsevctrs_{{ version }}.tar.gz
  sha256: 04f806ea5e3e7aae406e4aeb759df398b7a7871a812ee20681bdcb4dfafe3f8a

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib('c') }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib('m2w64_c') }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cli >=3.4.0
    - r-rlang >=1.1.0
    - r-vctrs
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-cli >=3.4.0
    - r-rlang >=1.1.0
    - r-vctrs

test:
  commands:
    - $R -e "library('sparsevctrs')"           # [not win]
    - "\"%R%\" -e \"library('sparsevctrs')\""  # [win]

about:
  home: https://github.com/r-lib/sparsevctrs, https://r-lib.github.io/sparsevctrs/
  license: MIT
  summary: Provides sparse vectors powered by ALTREP (Alternative Representations for R Objects)
    that behave like regular vectors, and can thus be used in data frames. Also provides
    tools to convert between sparse matrices and data frames with sparse columns and
    functions to interact with sparse vectors.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
